// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) error
	GetInsertedURL(ctx context.Context) (Url, error)
	IsShortCodeAvailable(ctx context.Context, shortCode string) (bool, error)
}

var _ Querier = (*Queries)(nil)
