// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: url.sql

package repo

import (
	"context"
)

const createURL = `-- name: CreateURL :exec
INSERT INTO urls (
    original_url,
    short_code,
    is_custom,
    expired_at
) VALUES (
    $1, $2, $3, $4
)
`

func (q *Queries) CreateURL(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createURL)
	return err
}

const getInsertedURL = `-- name: GetInsertedURL :one
SELECT id, original_url, short_code, is_custom, expired_at, created_at FROM urls WHERE id = LAST_INSERT_ID()
`

func (q *Queries) GetInsertedURL(ctx context.Context) (Url, error) {
	row := q.db.QueryRowContext(ctx, getInsertedURL)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.IsCustom,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}
